#!/bin/bash

__SCRIPTS_DIR__="$HOME/.scripts"
__SCRIPTS_BROWSER__="firefox"

if [ -z "$__SCRIPTS_OLD_PATH__" ]; then
    __SCRIPTS_OLD_PATH__=$PATH
    PATH=$PATH:$__SCRIPTS_DIR__/.bin
fi

export __SCRIPTS_DIR__
export __SCRIPTS_BROWSER__
export __SCRIPTS_OLD_PATH__
