#!/bin/bash

sudo killall qbittorrent &>/dev/null

sudo systemctl --force stop cups-browsed ModemManager avahi-daemon polipo \
privoxy plexmediaserver network-manager networking

sudo killall --wait wpa_suplicant

sudo rfkill unblock wlan

sudo ifconfig wlan0 down
sudo ifconfig wlan0 up

restart networking network-manager avahi-daemon polipo privoxy \
plexmediaserver

