#!/bin/bash

source $__SCRIPTS_DIR__/.functions/scripts_require

for PACKAGE in "ffmpeg:ffmpeg" "genisoimage:mkisofs" "dvdauthor:dvdauthor" "growisofs:growisofs"
do
  requires $PACKAGE
done


DEVICE=/dev/`readlink /dev/cdrom`
WRKDIR=$HOME/.dvdtemp/`date +%N`
MPGFILE=$WRKDIR/output.mpg
DVDFILE=$WRKDIR/dvd/
ISOFILE=$WRKDIR/output.iso

export VIDEO_FORMAT="NTSC"

# mkdir -p $HOME/.config
# echo NTSC > $HOME/.config/video_format

mkdir -p "$WRKDIR"

while (( "$#" )); do

ffmpeg -i "$1" -target ntsc-dvd -aspect 4:3 -ac 2 "$MPGFILE" && \
dvdauthor -t -o "$DVDFILE" --video=ntsc -f "$MPGFILE" && \
rm -rf "$MPGFILE" || echo FAIL

shift

done

dvdauthor -T -o "$DVDFILE"

mkisofs -dvd-video -o "$ISOFILE" "$DVDFILE" && \
growisofs -dvd-compat -Z $DEVICE="$ISOFILE" && \
rm -fr "$WRKDIR"
