#!/bin/bash

FILENAME=`realpath "$1"`
FILESIZE=$(stat -c%s "$FILENAME")

echo "Writing `basename $FILENAME` ( $FILESIZE ) to /dev/sdb..."

if [ ! -f $FILENAME ]; then
    echo "$FILENAME not found!"
else
    dd if=$FILENAME | pv --size $FILESIZE | dd of=/dev/sdb
fi
